Repository quarkiverse/quarkus-openapi-generator, pull requests merged in 2023-10, with the labels that each got.

#504 Add property additional-properties-as-attribute configuration
  README.md
  deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/CodegenConfig.java
  deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java
  deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/template/QuteTemplatingEngineAdapter.java
  deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/OpenApiClientGeneratorWrapper.java
  deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java
  deployment/src/main/resources/templates/libraries/microprofile/pojo.qute
  deployment/src/main/resources/templates/libraries/microprofile/pojoAdditionalProperties.qute
  docs/modules/ROOT/pages/additional-properties-as-attribute.adoc
  docs/modules/ROOT/pages/config.adoc
  integration-tests/additional-properties/pom.xml
  integration-tests/additional-properties/src/main/openapi/no-additional-properties-as-attr.yaml
  integration-tests/additional-properties/src/main/openapi/with-additional-properties-as-attr.yaml
  integration-tests/additional-properties/src/main/resources/application.properties
  integration-tests/additional-properties/src/test/java/io/quarkiverse/openapi/generator/additionalproperties/QuarkusAdditionalPropertiesAsAttributeAsFalseTest.java
  integration-tests/additional-properties/src/test/java/io/quarkiverse/openapi/generator/additionalproperties/QuarkusAdditionalPropertiesAsAttributeTrueTest.java
  integration-tests/pom.xml
Labels: backport-quarkus2

#509 Issue 437: Configurable API key header with Authorization header value
  README.md
  runtime/src/main/java/io/quarkiverse/openapi/generator/providers/ApiKeyAuthenticationProvider.java
  runtime/src/test/java/io/quarkiverse/openapi/generator/providers/ApiKeyAuthenticationProviderTest.java
Labels: backport-quarkus2

#524 Rename fromValue to fromString in Enum classes
  deployment/src/main/resources/templates/libraries/microprofile/enumClass.qute
  deployment/src/main/resources/templates/libraries/microprofile/enumOuterClass.qute
Labels: backport-main

#511 Actions to preview docs
  .github/workflows/build.yml
  .github/workflows/preview.yml
  .github/workflows/preview_teardown.yml
  README.md
  docs/modules/ROOT/pages/includes/additional-properties-as-attribute.adoc
  docs/modules/ROOT/pages/includes/config.adoc
  docs/modules/ROOT/pages/index.adoc
  docs/pom.xml
  pom.xml
Labels: documentation

#541 Fixes wrong behavior with right enum name
  deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegen.java
  deployment/src/test/java/io/quarkiverse/openapi/generator/deployment/wrapper/QuarkusJavaClientCodegenTest.java
Labels: backport-quarkus2
